// AUTO-GENERATED STUB — do not edit manually.
// Regenerate: npm run generate:sdk-shims
// Source: openclaw/src/plugin-sdk/testing.ts

const _warned = new Set();
function _w(fn) {
  if (!_warned.has(fn)) { _warned.add(fn); console.warn('[sdk-shim] openclaw/plugin-sdk/testing.' + fn + '() not implemented in Bridge mode'); }
}

export function createAckReactionHandle() { _w('createAckReactionHandle'); return undefined; }
export function removeAckReactionAfterReply() { _w('removeAckReactionAfterReply'); return undefined; }
export function removeAckReactionHandleAfterReply() { _w('removeAckReactionHandleAfterReply'); return undefined; }
export function shouldAckReaction() { _w('shouldAckReaction'); return false; }
export function expectChannelInboundContextContract() { _w('expectChannelInboundContextContract'); return undefined; }
export function primeChannelOutboundSendMock() { _w('primeChannelOutboundSendMock'); return undefined; }
export function installChannelOutboundPayloadContractSuite() { _w('installChannelOutboundPayloadContractSuite'); return undefined; }
export function buildDispatchInboundCaptureMock() { _w('buildDispatchInboundCaptureMock'); return undefined; }
export function createCliRuntimeCapture() { _w('createCliRuntimeCapture'); return undefined; }
export function firstWrittenJsonArg() { _w('firstWrittenJsonArg'); return undefined; }
export function spyRuntimeErrors() { _w('spyRuntimeErrors'); return undefined; }
export function spyRuntimeJson() { _w('spyRuntimeJson'); return undefined; }
export function spyRuntimeLogs() { _w('spyRuntimeLogs'); return undefined; }
export function setDefaultChannelPluginRegistryForTests() { _w('setDefaultChannelPluginRegistryForTests'); return undefined; }
export function isAtLeast() { _w('isAtLeast'); return false; }
export function parseSemver() { _w('parseSemver'); return undefined; }
export function callGateway() { _w('callGateway'); return undefined; }
export function deliverOutboundPayloads() { _w('deliverOutboundPayloads'); return undefined; }
export function createEmptyPluginRegistry() { _w('createEmptyPluginRegistry'); return undefined; }
export function createPluginRegistry() { _w('createPluginRegistry'); return undefined; }
export function providerContractLoadError() { _w('providerContractLoadError'); return undefined; }
export function pluginRegistrationContractRegistry() { _w('pluginRegistrationContractRegistry'); return undefined; }
export function resolveProviderContractProvidersForPluginIds() { _w('resolveProviderContractProvidersForPluginIds'); return undefined; }
export function resolveWebFetchProviderContractEntriesForPluginId() { _w('resolveWebFetchProviderContractEntriesForPluginId'); return undefined; }
export function resolveWebSearchProviderContractEntriesForPluginId() { _w('resolveWebSearchProviderContractEntriesForPluginId'); return undefined; }
export function loadPluginManifestRegistry() { _w('loadPluginManifestRegistry'); return undefined; }
export function parseMinHostVersionRequirement() { _w('parseMinHostVersionRequirement'); return undefined; }
export function resolveBundledExplicitProviderContractsFromPublicArtifacts() { _w('resolveBundledExplicitProviderContractsFromPublicArtifacts'); return undefined; }
export function expectAugmentedCodexCatalog() { _w('expectAugmentedCodexCatalog'); return undefined; }
export function expectedAugmentedOpenaiCodexCatalogEntriesWithGpt55() { _w('expectedAugmentedOpenaiCodexCatalogEntriesWithGpt55'); return undefined; }
export function expectedOpenaiPluginCodexCatalogEntriesWithGpt55() { _w('expectedOpenaiPluginCodexCatalogEntriesWithGpt55'); return undefined; }
export function expectCodexMissingAuthHint() { _w('expectCodexMissingAuthHint'); return undefined; }
export function initializeGlobalHookRunner() { _w('initializeGlobalHookRunner'); return undefined; }
export function resetGlobalHookRunner() { _w('resetGlobalHookRunner'); return undefined; }
export function addTestHook() { _w('addTestHook'); return undefined; }
export function assertUniqueValues() { _w('assertUniqueValues'); return undefined; }
export const BUNDLED_RUNTIME_SIDECAR_PATHS = undefined;
export function createPluginRecord() { _w('createPluginRecord'); return undefined; }
export function resolveBundledExplicitWebFetchProvidersFromPublicArtifacts() { _w('resolveBundledExplicitWebFetchProvidersFromPublicArtifacts'); return undefined; }
export function resolveBundledExplicitWebSearchProvidersFromPublicArtifacts() { _w('resolveBundledExplicitWebSearchProvidersFromPublicArtifacts'); return undefined; }
export function getActivePluginRegistry() { _w('getActivePluginRegistry'); return undefined; }
export function releasePinnedPluginChannelRegistry() { _w('releasePinnedPluginChannelRegistry'); return undefined; }
export function resetPluginRuntimeStateForTest() { _w('resetPluginRuntimeStateForTest'); return undefined; }
export function setActivePluginRegistry() { _w('setActivePluginRegistry'); return undefined; }
export function listImportedBundledPluginFacadeIds() { _w('listImportedBundledPluginFacadeIds'); return []; }
export function resetFacadeRuntimeStateForTest() { _w('resetFacadeRuntimeStateForTest'); return undefined; }
export function capturePluginRegistration() { _w('capturePluginRegistration'); return undefined; }
export function runProviderCatalog() { _w('runProviderCatalog'); return undefined; }
export function buildProviderPluginMethodChoice() { _w('buildProviderPluginMethodChoice'); return undefined; }
export function resolveProviderModelPickerEntries() { _w('resolveProviderModelPickerEntries'); return undefined; }
export function resolveProviderWizardOptions() { _w('resolveProviderWizardOptions'); return undefined; }
export function setProviderWizardProvidersResolverForTest() { _w('setProviderWizardProvidersResolverForTest'); return undefined; }
export function resolveProviderPluginChoice() { _w('resolveProviderPluginChoice'); return undefined; }
export function createAuthCaptureJsonFetch() { _w('createAuthCaptureJsonFetch'); return undefined; }
export function createRequestCaptureJsonFetch() { _w('createRequestCaptureJsonFetch'); return undefined; }
export function installPinnedHostnameTestHooks() { _w('installPinnedHostnameTestHooks'); return undefined; }
export function createSingleUserPromptMessage() { _w('createSingleUserPromptMessage'); return undefined; }
export function extractNonEmptyAssistantText() { _w('extractNonEmptyAssistantText'); return undefined; }
export function isLiveProfileKeyModeEnabled() { _w('isLiveProfileKeyModeEnabled'); return false; }
export function isLiveTestEnabled() { _w('isLiveTestEnabled'); return false; }
export function createSandboxTestContext() { _w('createSandboxTestContext'); return undefined; }
export function writeSkill() { _w('writeSkill'); return undefined; }
export function castAgentMessage() { _w('castAgentMessage'); return undefined; }
export function makeAgentAssistantMessage() { _w('makeAgentAssistantMessage'); return undefined; }
export function makeAgentUserMessage() { _w('makeAgentUserMessage'); return undefined; }
export function collectProviderApiKeys() { _w('collectProviderApiKeys'); return []; }
export function isModelNotFoundErrorMessage() { _w('isModelNotFoundErrorMessage'); return false; }
export function isAuthErrorMessage() { _w('isAuthErrorMessage'); return false; }
export function isBillingErrorMessage() { _w('isBillingErrorMessage'); return false; }
export function isOverloadedErrorMessage() { _w('isOverloadedErrorMessage'); return false; }
export function isServerErrorMessage() { _w('isServerErrorMessage'); return false; }
export function isTimeoutErrorMessage() { _w('isTimeoutErrorMessage'); return false; }
export function maybeLoadShellEnvForGenerationProviders() { _w('maybeLoadShellEnvForGenerationProviders'); return undefined; }
export function __testing() { _w('__testing'); return undefined; }
export function acpManagerTesting() { _w('acpManagerTesting'); return undefined; }
export function runAcpRuntimeAdapterContract() { _w('runAcpRuntimeAdapterContract'); return undefined; }
export function handleAcpCommand() { _w('handleAcpCommand'); return undefined; }
export function buildCommandTestParams() { _w('buildCommandTestParams'); return undefined; }
export function peekSystemEvents() { _w('peekSystemEvents'); return undefined; }
export function resetSystemEventsForTest() { _w('resetSystemEventsForTest'); return undefined; }
export function isTruthyEnvValue() { _w('isTruthyEnvValue'); return false; }
export function getShellEnvAppliedKeys() { _w('getShellEnvAppliedKeys'); return undefined; }
export function encodePngRgba() { _w('encodePngRgba'); return ""; }
export function fillPixel() { _w('fillPixel'); return undefined; }
export function parseCsvFilter() { _w('parseCsvFilter'); return undefined; }
export function parseProviderModelMap() { _w('parseProviderModelMap'); return undefined; }
export function redactLiveApiKey() { _w('redactLiveApiKey'); return undefined; }
export const DEFAULT_LIVE_MUSIC_MODELS = undefined;
export function resolveConfiguredLiveMusicModels() { _w('resolveConfiguredLiveMusicModels'); return undefined; }
export function resolveLiveMusicAuthStore() { _w('resolveLiveMusicAuthStore'); return undefined; }
export function canRunBufferBackedImageToVideoLiveLane() { _w('canRunBufferBackedImageToVideoLiveLane'); return false; }
export function canRunBufferBackedVideoToVideoLiveLane() { _w('canRunBufferBackedVideoToVideoLiveLane'); return false; }
export const DEFAULT_LIVE_VIDEO_MODELS = undefined;
export function resolveConfiguredLiveVideoModels() { _w('resolveConfiguredLiveVideoModels'); return undefined; }
export function resolveLiveVideoAuthStore() { _w('resolveLiveVideoAuthStore'); return undefined; }
export function resolveLiveVideoResolution() { _w('resolveLiveVideoResolution'); return undefined; }
export function normalizeVideoGenerationDuration() { _w('normalizeVideoGenerationDuration'); return ""; }
export function parseVideoGenerationModelRef() { _w('parseVideoGenerationModelRef'); return undefined; }
export function jsonResponse() { _w('jsonResponse'); return undefined; }
export function requestBodyText() { _w('requestBodyText'); return undefined; }
export function requestUrl() { _w('requestUrl'); return undefined; }
export function mockPinnedHostnameResolution() { _w('mockPinnedHostnameResolution'); return undefined; }
export function createOutboundTestPlugin() { _w('createOutboundTestPlugin'); return undefined; }
export function createTestRegistry() { _w('createTestRegistry'); return undefined; }
export function createWindowsCmdShimFixture() { _w('createWindowsCmdShimFixture'); return undefined; }
export function installCommonResolveTargetErrorCases() { _w('installCommonResolveTargetErrorCases'); return undefined; }
export function sanitizeTerminalText() { _w('sanitizeTerminalText'); return ""; }
export function withStateDirEnv() { _w('withStateDirEnv'); return undefined; }
export function countLines() { _w('countLines'); return undefined; }
export function hasBalancedFences() { _w('hasBalancedFences'); return false; }
export function expectGeneratedTokenPersistedToGatewayAuth() { _w('expectGeneratedTokenPersistedToGatewayAuth'); return undefined; }
export function captureEnv() { _w('captureEnv'); return undefined; }
export function withEnv() { _w('withEnv'); return undefined; }
export function withEnvAsync() { _w('withEnvAsync'); return undefined; }
export function withFetchPreconnect() { _w('withFetchPreconnect'); return undefined; }
export function createMockServerResponse() { _w('createMockServerResponse'); return undefined; }
export function registerProviderPlugin() { _w('registerProviderPlugin'); return undefined; }
export function registerProviderPlugins() { _w('registerProviderPlugins'); return undefined; }
export function registerSingleProviderPlugin() { _w('registerSingleProviderPlugin'); return undefined; }
export function requireRegisteredProvider() { _w('requireRegisteredProvider'); return undefined; }
export function createTempHomeEnv() { _w('createTempHomeEnv'); return undefined; }
export function withTempDir() { _w('withTempDir'); return undefined; }
export function typedCases() { _w('typedCases'); return undefined; }
export function createProviderUsageFetch() { _w('createProviderUsageFetch'); return undefined; }
export function makeResponse() { _w('makeResponse'); return undefined; }
export function useFrozenTime() { _w('useFrozenTime'); return undefined; }
export function useRealTime() { _w('useRealTime'); return undefined; }
export function createNonExitingRuntimeEnv() { _w('createNonExitingRuntimeEnv'); return undefined; }
export function createNonExitingTypedRuntimeEnv() { _w('createNonExitingTypedRuntimeEnv'); return undefined; }
export function createRuntimeEnv() { _w('createRuntimeEnv'); return undefined; }
export function createTypedRuntimeEnv() { _w('createTypedRuntimeEnv'); return undefined; }
export function createPluginSetupWizardAdapter() { _w('createPluginSetupWizardAdapter'); return undefined; }
export function createPluginSetupWizardConfigure() { _w('createPluginSetupWizardConfigure'); return undefined; }
export function createPluginSetupWizardStatus() { _w('createPluginSetupWizardStatus'); return undefined; }
export function createQueuedWizardPrompter() { _w('createQueuedWizardPrompter'); return undefined; }
export function createSetupWizardAdapter() { _w('createSetupWizardAdapter'); return undefined; }
export function createTestWizardPrompter() { _w('createTestWizardPrompter'); return undefined; }
export function promptSetupWizardAllowFrom() { _w('promptSetupWizardAllowFrom'); return undefined; }
export function resolveSetupWizardAllowFromEntries() { _w('resolveSetupWizardAllowFromEntries'); return undefined; }
export function resolveSetupWizardGroupAllowlist() { _w('resolveSetupWizardGroupAllowlist'); return undefined; }
export function runSetupWizardConfigure() { _w('runSetupWizardConfigure'); return undefined; }
export function runSetupWizardFinalize() { _w('runSetupWizardFinalize'); return undefined; }
export function runSetupWizardPrepare() { _w('runSetupWizardPrepare'); return undefined; }
export function selectFirstWizardOption() { _w('selectFirstWizardOption'); return undefined; }
export function createMockPluginRegistry() { _w('createMockPluginRegistry'); return undefined; }
export function buildPluginApi() { _w('buildPluginApi'); return undefined; }
export function createCapturedPluginRegistration() { _w('createCapturedPluginRegistration'); return undefined; }
export function createRuntimeTaskFlow() { _w('createRuntimeTaskFlow'); return undefined; }
